from agent_factory.control.modes import ABSOLUTE_JOINT, ABSOLUTE_POSE, DELTA_POSE

SUPPORTED_FORWARD_TRANSFORMS = {
    (ABSOLUTE_JOINT, ABSOLUTE_JOINT),
    (ABSOLUTE_POSE, ABSOLUTE_POSE),
    (DELTA_POSE, ABSOLUTE_POSE),
}

SUPPORTED_INVERSE_TRANSFORMS = {
    (ABSOLUTE_JOINT, ABSOLUTE_JOINT),
    (ABSOLUTE_POSE, ABSOLUTE_POSE),
    (ABSOLUTE_POSE, DELTA_POSE),
}
