agent_type: Diffusion_ITQC
device: cuda
seed: 42
soft_update_tau: 0.005
reward_scale: 100.0
env:
  env_id: StackCube-v1
  library: mani_skill
  env_config_path: ''
  action_dim: 7
  proprio_dim: 25
  server_mode: false
  obs_horizon: 2
  pred_horizon: 16
  act_horizon: 8
  num_cameras: 2
  obs_mode: rgb
  control_mode: pd_ee_delta_pose
  reward_mode: sparse
  render_mode: rgb_array
  max_episode_steps: 150
  gamma: 0.99
  penalty: -150.0
  reward_scale: 100
  reward_shape: false
train:
  batch_size: 32
  num_workers: 0
  n_epochs: 1000
  save_interval: 5000
dataset:
  include_rgb: true
  include_depth: false
  expert:
    demo_path: data/demos/expert_data.hdf5
    num_traj: null
    format: flat
  replay:
    max_traj_num: 100
runner:
  control_hz: 10
  buffer_capacity: 100
  redundancy_margin: 100
  save_dir: data
  hitl_enabled: false
  hitl_override_key: t
  hitl_source: keyboard
  hitl_finalize_intervention: true
actor:
  type: conditional_diffusion
  obs_horizon: 2
  action_dim: 10
  pred_horizon: 16
  require_env_action_dim_match: true
  norm:
    type: min_max
    params: {}
  use_extra_cond: false
  lr: 0.0001
  weight_decay: 1.0e-06
  cond_dim: 1
  cond_embed_dim: 32
  use_cfg_loss: false
  cfg_drop_rate: 0.1
  guidance_scale: 2.0
  unet:
    down_dims:
    - 128
    - 256
    - 512
    diffusion_step_embed_dim: 64
    n_groups: 8
  scheduler:
    num_train_timesteps: 100
    beta_schedule: squaredcos_cap_v2
  encoder:
    visual:
      in_channels: 3
      out_dim: 256
      backbone_type: plain
      pool_feature_map: true
      use_group_norm: true
    proprio_dim: 0
    out_dim: 256
    view_fusion: concat
  CFG_alpha: 0.4
critic:
  type: itqc
  encoder:
    visual:
      in_channels: 3
      out_dim: 256
      backbone_type: plain
      pool_feature_map: true
      use_group_norm: true
    proprio_dim: 0
    out_dim: 256
    view_fusion: concat
  hidden_dims:
  - 256
  - 256
  lr: 0.0002
  num_critics: 5
  num_quantiles: 5
  mc_loss_weight: 0.8
  quantile_huber_kappa: 1.0
agent_sp:
  threshold_quantile_offline: 0.8
  offline_iters_critic: 12000
  offline_iters_actor: 80000
  save_dir: run_results/ITQC
  exp_name: ''
  threshold_quantile_online: 0.3
  online_iters_critic: 20000
  online_iters_actor: 10000
  only_suc: true
